name: binghan_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  get_it: 8.2.0
  provider: 6.1.5+1
  rflutter_alert: 2.0.7
  http: 1.5.0
  shared_preferences: 2.5.3
  fl_chart: 1.1.1
  # find_dropdown: 1.0.0
  image_picker: 1.2.0
  # flutter_money_formatter: ^0.8.3
  badges: ^3.1.2
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.1
  dio: ^5.9.0
  # flushbar: ^1.9.1
  another_flushbar: ^1.12.32
  mask_text_input_formatter: ^2.9.0
  firebase_messaging: ^16.0.3
  auto_size_text: ^3.0.0
  date_format: ^2.0.9
  webview_flutter: ^4.13.0
  image_cropper: ^11.0.0
  board_datetime_picker: ^2.8.4
  fluttertoast: ^9.0.0
  url_launcher: ^6.3.2
  # package_info: '>=0.4.3 <2.0.0'
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
